// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ci1e9frl1mpwNPwpmrZ5O7gGBV0RW7I',
    appId: '1:564165807972:web:114de9f3df8a85bb7c3471',
    messagingSenderId: '564165807972',
    projectId: 'commad-line-cli',
    authDomain: 'commad-line-cli.firebaseapp.com',
    storageBucket: 'commad-line-cli.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16b8qebKWGFj7JNfkU55xMgKc6ZT4Lhs',
    appId: '1:564165807972:android:71f7b68811824b817c3471',
    messagingSenderId: '564165807972',
    projectId: 'commad-line-cli',
    storageBucket: 'commad-line-cli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlvEM0pw6rKDntA9btmszcN9B6BgU6CKk',
    appId: '1:564165807972:ios:35bc1fb9e3e0d3267c3471',
    messagingSenderId: '564165807972',
    projectId: 'commad-line-cli',
    storageBucket: 'commad-line-cli.firebasestorage.app',
    iosBundleId: 'com.example.commandlinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlvEM0pw6rKDntA9btmszcN9B6BgU6CKk',
    appId: '1:564165807972:ios:35bc1fb9e3e0d3267c3471',
    messagingSenderId: '564165807972',
    projectId: 'commad-line-cli',
    storageBucket: 'commad-line-cli.firebasestorage.app',
    iosBundleId: 'com.example.commandlinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ci1e9frl1mpwNPwpmrZ5O7gGBV0RW7I',
    appId: '1:564165807972:web:efe3dfa45d538bf57c3471',
    messagingSenderId: '564165807972',
    projectId: 'commad-line-cli',
    authDomain: 'commad-line-cli.firebaseapp.com',
    storageBucket: 'commad-line-cli.firebasestorage.app',
  );
}
